services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydb
      - HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: mydb
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
